service: ${self:custom.name}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'production'}
  region: ap-southeast-1

plugins:
  - serverless-nextjs-plugin

custom:
  name: afn-contentful-next
  serverless-nextjs:
    assetsBucketName: 'afn-contentful-next-${self:provider.stage}'

package:
  exclude:
    - ./**